from tkinter import *
a=Tk()
a.geometry('1500x1500')
b=Label(a,text="Welcome User",font=("MV Boli",15,'bold'),bg='black',fg='red')
b.place(x=500,y=200)
c=Label(a,text="User Name",font=("MV Boli",15,'bold'),bg='black',fg='red')
c.place(x=450,y=300)
d=Entry(a,width=20,justify='center')
d.place(x=570,y=310)
e=Label(a,text="Password",font=("MV Boli",15,'bold'),bg='black',fg='red')
e.place(x=450,y=350)
f=Entry(a,width=20,justify='center')
f.place(x=570,y=355)
def new():
    g=Frame(a,bg="black",width='1500',height='1500')
    g.place(x=0,y=0)
    h=Label(g,text="Name",font=("MV Boli",15,'bold'),bg='black',fg='red')
    h.place(x=450,y=300)
    i=Entry(g,width=20,justify='center')
    i.place(x=570,y=300)
    j=Label(g,text="Email",font=("MV Boli",15,'bold'),bg='black',fg='red')
    j.place(x=450,y=340)
    k=Entry(g,width=20,justify='center')
    k.place(x=570,y=345)
    l=Label(g,text="Phone",font=("MV Boli",15,'bold'),bg='black',fg='red')
    l.place(x=450,y=380)
    m=Entry(g,width=20,justify='center')
    m.place(x=570,y=385)
    n=Label(g,text="Address",font=("MV Boli",15,'bold'),bg='black',fg='red')
    n.place(x=450,y=420)
    o=Entry(g,width=20,justify='center')
    o.place(x=570,y=425)
    p=Button(g,text="Submit",font=("MV Boli",15,'bold'),bg='black',fg='red')
    p.place(x=450,y=470)
    def bc():
        g.destroy()
    r=Button(g,text="Cancel",font=("MV Boli",15,'bold'),bg='black',fg='red',command=bc)
    r.place(x=560,y=470)
s=Button(a,text="New User",font=("MV Boli",15,'bold'),bg='black',fg='red',command=new)
s.place(x=510,y=440)
